=encoding utf8

=head1 NAME

HTML5::DOM - Super fast html5 DOM library with css selectors (based on Modest/MyHTML)

=for html <a href="https://travis-ci.org/Azq2/perl-html5-dom"><img src="https://travis-ci.org/Azq2/perl-html5-dom.svg?branch=master"></a>

=head1 SYNOPSIS

=head1 DESCRIPTION

L<HTML5::DOM> is a fast HTML5 parser and DOM manipulatin library with CSS4 selector, fully conformant with the HTML5 specification.
It based on  L<https://github.com/lexborisov/Modest> as selector engine and L<https://github.com/lexborisov/myhtml> as HTML5 parser. 

=head1 METHODS

L<HTML5::DOM> implements the following methods.

=head2 new

=head3 new($options)

 # with default options
 my $parser = HTML5::DOM->new;
 
 # override some options, if you need
 my $parser = HTML5::DOM->new({
    threads             => 2,
    async               => 0, 
    ignore_whitespace   => 0, 
    ignore_doctype      => 0, 
    scripts             => 0, 
    encoding            => "auto", 
    default_encoding    => "UTF-8", 
    encoding_use_meta   => 1, 
    encoding_use_bom    => 1, 
 });

Creates new parser object with options. See L<"PARSER OPTIONS"> for details. 

=head1 PARSER OPTIONS

Options for L<HTML5::DOM::new>, L<HTML5::DOM::parse>, L<HTML5::DOM::new>, L<HTML5::DOM::Node::parseFragment>

=head4 threads

Threads count, if 0 - parsing in single mode without threads (default 2)

=head4 async

If async 0 (default), then some parse functions L<HTML5::DOM::Node::parseFragment|/parseFragment>, L<HTML5::DOM::parse|/parse>, L<HTML5::DOM::parseChunkEnd|/parseChunkEnd> waiting for parsing done.

If async 1, you must manualy call L<HTML5::DOM::Node::wait|/wait> and L<HTML5::DOM::Tree::wait|/wait> for waiting parsing of node or tree done or 
L<HTML5::DOM::Node::parsed|/parsed>, L<HTML5::DOM::Node::parsed|/parsed> to non-blocking determine parsing done.

This options affects only if threads > 0

=head4 ignore_whitespace

Ignore whitespace tokens (default 0)

=head4 ignore_doctype

Do not parse DOCTYPE (default 0)

=head4 scripts

If 1 - <noscript> contents parsed to single text node (default)

If 0 - <noscript> contents parsed to child nodes

=head4 encoding

Encoding of input HTML, if auto - library can tree to automaticaly determine encoding. (default "auto")

=head4 default_encoding

Default encoding, this affects only if encoding set to "auto" and encoding not determined. (default "UTF-8")

=head4 encoding_use_meta

Allow use <meta> tags to determine input HTML encoding. (default 1)

=head4 encoding_use_bom

Allow use detecding BOM to determine input HTML encoding. (default 1)
